import { describe, it, expect, afterEach } from "bun:test"
import { mkdtempSync, rmSync, existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { execFileSync } from "node:child_process"

const CLI_PATH = join(import.meta.dir, "..", "src", "index.ts")

function makeFixture(prefix: string) {
  return mkdtempSync(join(tmpdir(), `bettercode-cli-${prefix}-`))
}

let fixtureDir: string

afterEach(() => {
  if (fixtureDir) {
    rmSync(fixtureDir, { recursive: true, force: true })
    fixtureDir = ""
  }
})

function runCli(args: string[], cwd: string) {
  return execFileSync("bun", ["run", CLI_PATH, ...args], {
    cwd,
    encoding: "utf8",
    timeout: 30000,
    stdio: ["pipe", "pipe", "pipe"],
  })
}

describe("bettercode init", () => {
  it("creates .bettercode directory structure", () => {
    fixtureDir = makeFixture("init")
    const output = runCli(["init"], fixtureDir)

    expect(output).toContain("BetterCode initialized")
    expect(existsSync(join(fixtureDir, ".bettercode", "quality-gate.json"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "profile.md"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "commands.md"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "architecture.md"))).toBe(true)
  })

  it("creates .bettercode with --json flag", () => {
    fixtureDir = makeFixture("init-json")
    const output = runCli(["--json", "init"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed.status).toBe("ok")
    expect(parsed.created).toContain("quality-gate.json")
  })

  it("does not overwrite existing files", () => {
    fixtureDir = makeFixture("init-existing")
    mkdirSync(join(fixtureDir, ".bettercode", "brain"), { recursive: true })
    const existingContent = "# Custom Profile\n"
    writeFileSync(join(fixtureDir, ".bettercode", "brain", "profile.md"), existingContent)

    runCli(["init"], fixtureDir)

    const content = readFileSync(join(fixtureDir, ".bettercode", "brain", "profile.md"), "utf8")
    expect(content).toBe(existingContent)
  })
})

describe("bettercode sync", () => {
  it("creates .opencode/plugin/bettercode.ts", () => {
    fixtureDir = makeFixture("sync")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    const output = runCli(["sync"], fixtureDir)

    expect(output).toContain("BetterCode plugin registered")
    expect(existsSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"))).toBe(true)

    const pluginContent = readFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), "utf8")
    expect(pluginContent).toContain('bettercode-plugin')
    expect(pluginContent).toContain("Auto-generated by bettercode sync")
  })

  it("is idempotent", () => {
    fixtureDir = makeFixture("sync-idempotent")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    runCli(["sync"], fixtureDir)
    runCli(["sync"], fixtureDir)

    const content = readFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), "utf8")
    expect(content).toContain("Auto-generated by bettercode sync")
  })

  it("preserves existing .opencode/opencode.jsonc fields", () => {
    fixtureDir = makeFixture("sync-preserve")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{\n  "provider": { "openai": {} },\n  "mcp": {}\n}\n')

    runCli(["sync"], fixtureDir)

    const config = JSON.parse(readFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), "utf8"))
    expect(config.provider).toEqual({ openai: {} })
    expect(config.mcp).toEqual({})
  })

  it("creates .opencode/ if missing", () => {
    fixtureDir = makeFixture("sync-no-opencode")
    runCli(["sync"], fixtureDir)

    expect(existsSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"))).toBe(true)
  })

  it("works with --json flag", () => {
    fixtureDir = makeFixture("sync-json")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    const output = runCli(["--json", "sync"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed.status).toBe("ok")
    expect(parsed.pluginFile).toBe(".opencode/plugin/bettercode.ts")
  })
})

describe("bettercode doctor", () => {
  it("reports ok for valid setup", () => {
    fixtureDir = makeFixture("doctor-valid")
    // Create minimal valid setup
    mkdirSync(join(fixtureDir, ".opencode", "plugin"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), 'export { default } from "../../packages/bettercode-plugin/src/index.ts"\nexport * from "../../packages/bettercode-plugin/src/index.ts"\n')
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("OpenCode CLI")
    expect(output).toContain("bettercode-plugin")
    expect(output).toContain("Health check")
  })

  it("warns when .opencode/plugin is missing", () => {
    fixtureDir = makeFixture("doctor-no-plugin")
    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("Plugin registration")
    expect(output).toContain("not found")
  })

  it("warns when .bettercode config is missing", () => {
    fixtureDir = makeFixture("doctor-no-config")
    mkdirSync(join(fixtureDir, ".opencode", "plugin"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), 'export { default } from "../../packages/bettercode-plugin/src/index.ts"\n')

    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("BetterCode config")
    expect(output).toContain("not found")
  })

  it("reports error for invalid JSONC", () => {
    fixtureDir = makeFixture("doctor-invalid")
    mkdirSync(join(fixtureDir, ".bettercode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".bettercode", "bettercode.jsonc"), '{ invalid json!!! }')

    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("BetterCode config")
    expect(output).toContain("invalid")
  })

  it("works with --json flag", () => {
    fixtureDir = makeFixture("doctor-json")
    const output = runCli(["--json", "doctor"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(Array.isArray(parsed)).toBe(true)
    expect(parsed.length).toBeGreaterThan(0)
    expect(parsed[0]).toHaveProperty("name")
    expect(parsed[0]).toHaveProperty("status")
  })
})

describe("bettercode sync with pluginOptions", () => {
  it("writes plugin options to .opencode/opencode.jsonc", () => {
    fixtureDir = makeFixture("sync-options")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')
    mkdirSync(join(fixtureDir, ".bettercode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".bettercode", "bettercode.jsonc"), '{"plugin": {"brain": {"autoInject": true}}}\n')

    runCli(["sync"], fixtureDir)

    const config = JSON.parse(readFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), "utf8"))
    expect(Array.isArray(config.plugin)).toBe(true)
    expect(config.plugin.length).toBe(1)
    const entry = config.plugin[0]
    expect(entry[0]).toBe("./plugin/bettercode.ts")
    expect(entry[1]).toEqual({ brain: { autoInject: true } })
  })

  it("updates existing plugin entry without duplication", () => {
    fixtureDir = makeFixture("sync-update")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{"plugin": [["./plugin/bettercode.ts", {"brain": {"autoInject": false}}]]}\n')
    mkdirSync(join(fixtureDir, ".bettercode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".bettercode", "bettercode.jsonc"), '{"plugin": {"brain": {"autoInject": true, "maxTokens": 3000}}}\n')

    runCli(["sync"], fixtureDir)

    const config = JSON.parse(readFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), "utf8"))
    expect(config.plugin.length).toBe(1)
    expect(config.plugin[0][1]).toEqual({ brain: { autoInject: true, maxTokens: 3000 } })
  })
})

describe("bettercode gate run", () => {
  it("outputs quality gate result in JSON", () => {
    fixtureDir = makeFixture("gate")
    const output = runCli(["--json", "gate", "run"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed).toHaveProperty("status")
    expect(parsed).toHaveProperty("score")
    expect(parsed).toHaveProperty("risk")
    expect(parsed).toHaveProperty("checks")
  })
})

describe("bettercode brain", () => {
  it("brain init creates brain files", () => {
    fixtureDir = makeFixture("brain-init")
    const output = runCli(["brain", "init"], fixtureDir)

    expect(output).toContain("Brain initialized")
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "profile.md"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "architecture.md"))).toBe(true)
  })

  it("brain search returns no-results for empty brain", () => {
    fixtureDir = makeFixture("brain-search")
    const output = runCli(["brain", "search", "nonexistent"], fixtureDir)

    expect(output).toContain("No results")
  })

  it("brain update updates profile", () => {
    fixtureDir = makeFixture("brain-update")
    runCli(["brain", "init"], fixtureDir)
    const output = runCli(["brain", "update"], fixtureDir)

    expect(output).toContain("Brain updated")
  })
})

describe("bettercode benchmark run", () => {
  it("runs and outputs score", () => {
    fixtureDir = makeFixture("benchmark")
    const output = runCli(["--json", "benchmark", "run"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed).toHaveProperty("score")
    expect(parsed).toHaveProperty("duration_ms")
  })
})

describe("bettercode report", () => {
  it("generates report", () => {
    fixtureDir = makeFixture("report")
    const output = runCli(["--json", "report"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed).toHaveProperty("gate")
    expect(parsed).toHaveProperty("brain")
  })
})

describe("bettercode run", () => {
  it("reports missing OpenCode CLI entry", () => {
    fixtureDir = makeFixture("run-missing")
    try {
      runCli(["run", "--", "--help"], fixtureDir)
    } catch (e: any) {
      expect(e.stderr).toContain("OpenCode CLI entry not found")
    }
  })
})
