import { describe, it, expect, afterEach, beforeAll } from "bun:test"
import { mkdtempSync, rmSync, existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { execFileSync } from "node:child_process"

const CLI_PATH = join(import.meta.dir, "..", "src", "index.ts")

function makeFixture(prefix: string) {
  return mkdtempSync(join(tmpdir(), `bettercode-cli-${prefix}-`))
}

let fixtureDir: string

afterEach(() => {
  if (fixtureDir) {
    rmSync(fixtureDir, { recursive: true, force: true })
    fixtureDir = ""
  }
})

function runCli(args: string[], cwd: string) {
  return execFileSync("bun", ["run", CLI_PATH, ...args], {
    cwd,
    encoding: "utf8",
    timeout: 30000,
    stdio: ["pipe", "pipe", "pipe"],
  })
}

describe("bettercode init", () => {
  it("creates .bettercode directory structure", () => {
    fixtureDir = makeFixture("init")
    const output = runCli(["init"], fixtureDir)

    expect(output).toContain("BetterCode initialized")
    expect(existsSync(join(fixtureDir, ".bettercode", "quality-gate.json"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "profile.md"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "commands.md"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "architecture.md"))).toBe(true)
  })

  it("creates .bettercode with --json flag", () => {
    fixtureDir = makeFixture("init-json")
    const output = runCli(["--json", "init"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed.status).toBe("ok")
    expect(parsed.created).toContain("quality-gate.json")
  })

  it("does not overwrite existing files", () => {
    fixtureDir = makeFixture("init-existing")
    mkdirSync(join(fixtureDir, ".bettercode", "brain"), { recursive: true })
    const existingContent = "# Custom Profile\n"
    writeFileSync(join(fixtureDir, ".bettercode", "brain", "profile.md"), existingContent)

    runCli(["init"], fixtureDir)

    const content = readFileSync(join(fixtureDir, ".bettercode", "brain", "profile.md"), "utf8")
    expect(content).toBe(existingContent)
  })
})

describe("bettercode sync", () => {
  it("creates .opencode/plugin/bettercode.ts", () => {
    fixtureDir = makeFixture("sync")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    const output = runCli(["sync"], fixtureDir)

    expect(output).toContain("BetterCode plugin registered")
    expect(existsSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"))).toBe(true)

    const pluginContent = readFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), "utf8")
    expect(pluginContent).toContain('@bettercode/plugin')
    expect(pluginContent).toContain("Auto-generated by bettercode sync")
  })

  it("is idempotent", () => {
    fixtureDir = makeFixture("sync-idempotent")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    runCli(["sync"], fixtureDir)
    runCli(["sync"], fixtureDir)

    const content = readFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), "utf8")
    expect(content).toContain("Auto-generated by bettercode sync")
  })

  it("preserves existing .opencode/opencode.jsonc fields", () => {
    fixtureDir = makeFixture("sync-preserve")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{\n  "provider": { "openai": {} },\n  "mcp": {}\n}\n')

    runCli(["sync"], fixtureDir)

    const config = JSON.parse(readFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), "utf8"))
    expect(config.provider).toEqual({ openai: {} })
    expect(config.mcp).toEqual({})
  })

  it("creates .opencode/ if missing", () => {
    fixtureDir = makeFixture("sync-no-opencode")
    runCli(["sync"], fixtureDir)

    expect(existsSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"))).toBe(true)
  })

  it("works with --json flag", () => {
    fixtureDir = makeFixture("sync-json")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    const output = runCli(["--json", "sync"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(parsed.status).toBe("ok")
    expect(parsed.pluginFile).toBe(".opencode/plugin/bettercode.ts")
  })
})

describe("bettercode doctor", () => {
  it("reports ok for valid setup", () => {
    fixtureDir = makeFixture("doctor-valid")
    // Create minimal valid setup
    mkdirSync(join(fixtureDir, ".opencode", "plugin"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), 'export { default } from "@bettercode/plugin"\nexport * from "@bettercode/plugin"\n')
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("OpenCode CLI")
    expect(output).toContain("@bettercode/plugin")
    expect(output).toContain("Health check")
  })

  it("warns when .opencode/plugin is missing", () => {
    fixtureDir = makeFixture("doctor-no-plugin")
    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("Plugin registration")
    expect(output).toContain("not found")
  })

  it("warns when .bettercode config is missing", () => {
    fixtureDir = makeFixture("doctor-no-config")
    mkdirSync(join(fixtureDir, ".opencode", "plugin"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), 'export { default } from "@bettercode/plugin"\n')

    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("BetterCode config")
    expect(output).toContain("not found")
  })

  it("reports error for invalid JSONC", () => {
    fixtureDir = makeFixture("doctor-invalid")
    mkdirSync(join(fixtureDir, ".bettercode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".bettercode", "bettercode.jsonc"), '{ invalid json!!! }')

    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("BetterCode config")
    expect(output).toContain("invalid")
  })

  it("works with --json flag", () => {
    fixtureDir = makeFixture("doctor-json")
    const output = runCli(["--json", "doctor"], fixtureDir)

    const parsed = JSON.parse(output)
    expect(Array.isArray(parsed)).toBe(true)
    expect(parsed.length).toBeGreaterThan(0)
    expect(parsed[0]).toHaveProperty("name")
    expect(parsed[0]).toHaveProperty("status")
  })
})
