import { describe, it, expect, afterEach } from "bun:test"
import { mkdtempSync, rmSync, existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"
import { execFileSync } from "node:child_process"

const CLI_PATH = join(import.meta.dir, "..", "src", "index.ts")

function makeFixture(prefix: string) {
  return mkdtempSync(join(tmpdir(), `bettercode-e2e-${prefix}-`))
}

function runCli(args: string[], cwd: string) {
  return execFileSync("bun", ["run", CLI_PATH, ...args], {
    cwd,
    encoding: "utf8",
    timeout: 30000,
    stdio: ["pipe", "pipe", "pipe"],
  })
}

function runCliSafe(args: string[], cwd: string) {
  try {
    return runCli(args, cwd)
  } catch (e: any) {
    return e.stdout || e.stderr || ""
  }
}

let fixtureDir: string

afterEach(() => {
  if (fixtureDir) {
    rmSync(fixtureDir, { recursive: true, force: true })
    fixtureDir = ""
  }
})

describe("E2E: fresh project workflow", () => {
  it("init → doctor → sync completes without error", () => {
    fixtureDir = makeFixture("e2e-fresh")

    const init = runCli(["init"], fixtureDir)
    expect(init).toContain("BetterCode initialized")

    const doctor = runCli(["doctor"], fixtureDir)
    expect(doctor).toContain("Health check")

    const sync = runCli(["sync"], fixtureDir)
    expect(sync).toContain("BetterCode plugin registered")

    expect(existsSync(join(fixtureDir, ".bettercode", "quality-gate.json"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".bettercode", "brain", "profile.md"))).toBe(true)
    expect(existsSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"))).toBe(true)
  })

  it("brain init → brain update → brain search works end-to-end", () => {
    fixtureDir = makeFixture("e2e-brain")

    const brainInit = runCli(["brain", "init"], fixtureDir)
    expect(brainInit).toContain("Brain initialized")

    const brainUpdate = runCli(["brain", "update"], fixtureDir)
    expect(brainUpdate).toContain("Brain updated")

    const brainSearch = runCliSafe(["brain", "search", "test"], fixtureDir)
    expect(brainSearch).toContain("result")
  })

  it("gate run produces valid JSON output", () => {
    fixtureDir = makeFixture("e2e-gate")

    const output = runCli(["--json", "gate", "run"], fixtureDir)
    const parsed = JSON.parse(output)

    expect(parsed).toHaveProperty("status")
    expect(parsed).toHaveProperty("score")
    expect(parsed).toHaveProperty("checks")
    expect(typeof parsed.score).toBe("number")
  })
})

describe("E2E: sync idempotency", () => {
  it("running sync 3 times produces identical plugin file", () => {
    fixtureDir = makeFixture("e2e-sync-idempotent")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{}\n')

    runCli(["sync"], fixtureDir)
    runCli(["sync"], fixtureDir)
    runCli(["sync"], fixtureDir)

    const content = readFileSync(join(fixtureDir, ".opencode", "plugin", "bettercode.ts"), "utf8")
    expect(content).toContain("Auto-generated by bettercode sync")
    expect(content).toContain('@bettercode/plugin')

    const config = JSON.parse(readFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), "utf8"))
    expect(config.plugin).toBeUndefined()
  })
})

describe("E2E: sync with plugin options", () => {
  it("writes options to opencode.jsonc and preserves existing fields", () => {
    fixtureDir = makeFixture("e2e-sync-options")
    mkdirSync(join(fixtureDir, ".opencode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), '{"provider": {"openai": {}}}\n')
    mkdirSync(join(fixtureDir, ".bettercode"), { recursive: true })
    writeFileSync(join(fixtureDir, ".bettercode", "bettercode.jsonc"), '{"plugin": {"brain": {"autoInject": true, "maxTokens": 3000}}}\n')

    runCli(["sync"], fixtureDir)

    const config = JSON.parse(readFileSync(join(fixtureDir, ".opencode", "opencode.jsonc"), "utf8"))
    expect(config.provider).toEqual({ openai: {} })
    expect(config.plugin).toEqual([["./plugin/bettercode.ts", { brain: { autoInject: true, maxTokens: 3000 } }]])
  })
})

describe("E2E: doctor detects issues", () => {
  it("reports errors for missing components", () => {
    fixtureDir = makeFixture("e2e-doctor-missing")
    const output = runCli(["doctor"], fixtureDir)

    expect(output).toContain("BetterCode config")
    expect(output).toContain("not found")
  })
})
