import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["BETTERCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["BETTERCODE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("BETTERCODE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  BETTERCODE_AUTO_HEAP_SNAPSHOT: truthy("BETTERCODE_AUTO_HEAP_SNAPSHOT"),
  BETTERCODE_GIT_BASH_PATH: process.env["BETTERCODE_GIT_BASH_PATH"],
  BETTERCODE_CONFIG: process.env["BETTERCODE_CONFIG"],
  BETTERCODE_CONFIG_CONTENT: process.env["BETTERCODE_CONFIG_CONTENT"],
  BETTERCODE_DISABLE_AUTOUPDATE: truthy("BETTERCODE_DISABLE_AUTOUPDATE"),
  BETTERCODE_ALWAYS_NOTIFY_UPDATE: truthy("BETTERCODE_ALWAYS_NOTIFY_UPDATE"),
  BETTERCODE_DISABLE_PRUNE: truthy("BETTERCODE_DISABLE_PRUNE"),
  BETTERCODE_DISABLE_TERMINAL_TITLE: truthy("BETTERCODE_DISABLE_TERMINAL_TITLE"),
  BETTERCODE_SHOW_TTFD: truthy("BETTERCODE_SHOW_TTFD"),
  BETTERCODE_DISABLE_AUTOCOMPACT: truthy("BETTERCODE_DISABLE_AUTOCOMPACT"),
  BETTERCODE_DISABLE_MODELS_FETCH: truthy("BETTERCODE_DISABLE_MODELS_FETCH"),
  BETTERCODE_DISABLE_MOUSE: truthy("BETTERCODE_DISABLE_MOUSE"),
  BETTERCODE_FAKE_VCS: process.env["BETTERCODE_FAKE_VCS"],
  BETTERCODE_SERVER_PASSWORD: process.env["BETTERCODE_SERVER_PASSWORD"],
  BETTERCODE_SERVER_USERNAME: process.env["BETTERCODE_SERVER_USERNAME"],
  BETTERCODE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("BETTERCODE_DISABLE_FFF"),

  // Experimental
  BETTERCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("BETTERCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BETTERCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("BETTERCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  BETTERCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("BETTERCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  BETTERCODE_MODELS_URL: process.env["BETTERCODE_MODELS_URL"],
  BETTERCODE_MODELS_PATH: process.env["BETTERCODE_MODELS_PATH"],
  BETTERCODE_DB: process.env["BETTERCODE_DB"],

  BETTERCODE_WORKSPACE_ID: process.env["BETTERCODE_WORKSPACE_ID"],
  BETTERCODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("BETTERCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get BETTERCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("BETTERCODE_DISABLE_PROJECT_CONFIG")
  },
  get BETTERCODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("BETTERCODE_EXPERIMENTAL_REFERENCES")
  },
  get BETTERCODE_TUI_CONFIG() {
    return process.env["BETTERCODE_TUI_CONFIG"]
  },
  get BETTERCODE_CONFIG_DIR() {
    return process.env["BETTERCODE_CONFIG_DIR"]
  },
  get BETTERCODE_PURE() {
    return truthy("BETTERCODE_PURE")
  },
  get BETTERCODE_PERMISSION() {
    return process.env["BETTERCODE_PERMISSION"]
  },
  get BETTERCODE_PLUGIN_META_FILE() {
    return process.env["BETTERCODE_PLUGIN_META_FILE"]
  },
  get BETTERCODE_CLIENT() {
    return process.env["BETTERCODE_CLIENT"] ?? "cli"
  },
}
